verbose: false

go:
    version: 1.14.6
    cgo: false

repository:
    path: github.com/criteo/go-biggraphite

build:
    prefix: .
    binaries:
        - name: bg-metadatawriter
          path: ./cmd/bg-metadatawriter

    flags: -a -tags netgo
    ldflags: |
        -s
        -X {{repoPath}}/version.Version={{.Version}}
        -X {{repoPath}}/version.Revision={{.Revision}}
        -X {{repoPath}}/version.Branch={{.Branch}}
        -X {{repoPath}}/version.BuildUser={{user}}@{{host}}
        -X {{repoPath}}/version.BuildDate={{date "20060102-15:04:05"}}

tarball:
    prefix: .
    files:
        - LICENSE


crossbuild:
    platforms:
        - linux/amd64
        - linux/386
        - darwin/amd64
        - darwin/386
        - windows/amd64
        - windows/386
